steps:
  - name: 'gcr.io/cloud-builders/gradle:5.6.2-jdk-8'
    args: ['build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/spring-boot-example', '.']
images: ['gcr.io/$PROJECT_ID/spring-boot-example:latest']